services:
  - type: web
    name: college-samaj-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: college_samaj_db
          property: connectionString
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: college_samaj_db
    databaseName: college_samaj
    user: college_samaj_user

packages:
  - Flask==2.1.0
  - Flask-SQLAlchemy==2.5.1
  - Flask-Bcrypt==0.7.1
  - Flask-JWT-Extended==4.3.1
  - Flask-CORS==3.0.10
  - Flask-Migrate==3.1.0
  - Flask-Mail==0.9.1
  - gunicorn==20.1.0
  - psycopg2-binary==2.9.3
  - python-dotenv